export default ProductData = [
  {
    id: 1,
    name: 'Burger',
    imageUrl: require('../assets/images/burger.jpg'),
    price: '150₹',
    idAdded: false,
  },
  {
    id: 2,
    name: 'Biryani',
    imageUrl: require('../assets/images/biryani.jpg'),
    price: '320₹',
    isAdded: false,
  },
  {
    id: 3,
    name: 'Salad',
    imageUrl: require('../assets/images/salad.jpg'),
    price: '120₹',
    isAdded: false,
  },
  {
    id: 4,
    name: 'Pasta',
    imageUrl: require('../assets/images/pasta.jpg'),
    price: '170₹',
    isAdded: false,
  },
  {
    id: 5,
    name: 'Sahi Paneer',
    imageUrl: require('../assets/images/sahiPaneer.jpg'),
    price: '200₹',
    isAdded: false,
  },
  {
    id: 6,
    name: 'Sweet',
    imageUrl: require('../assets/images/sweet.jpg'),
    price: '80₹',
    isAdded: false,
  },
  {
    id: 7,
    name: 'Greek Salad',
    imageUrl: require('../assets/images/greenSalad.jpg'),
    price: '110₹',
    isAdded: false,
  },
  {
    id: 8,
    name: 'Pizza',
    imageUrl: require('../assets/images/pizza.jpg'),
    price: '370₹',
    isAdded: false,
  },
  {
    id: 9,
    name: 'South Indian',
    imageUrl: require('../assets/images/southIndian.jpg'),
    price: '120₹',
    isAdded: false,
  },
];
